Studio di fattibilita
Omicron-Team/Documentazione pull request #21
Opened 2020-12-11 18:05 UTC by killbizz

- [ ]  Verificato

- [ ] Approvato

2020-12-14 09:25 UTC, nicomanto commented
**Verifica dall'inizio fino al capitolato C3 compreso**
- Nella prima pagina il tipo di data deve essere nella forma yyyy-mm-dd
- Nel registro delle modifiche non so se possiamo mettere il gruppo come autore
- Il diario delle modifiche dovrebbe andare dalla modifica più recente a quella più vecchia
- Nel punto 1.1 penso sarebbe meglio mettere un ; dopo la fine di ogni item 
- Nel punto 2.2 semplificherei un pò questa frase ```consenta il tracciamento immutabile e certificato tramite tag RFIDG delle presenze in tempo reale alle postazioni di lavoro di un laboratorio informatico```
- Nel punto 2.6 risciverei meglio ```Possibile difficolta nell’apprendimento di alcune complesse tecnologie coinvolte per
i membri del gruppo che non le hanno mai utilizzate precedentemente.```
- Nel punto 3.6 penso che i business requirements non siano necessari, quindi per me si possono togliere
- Nel punto 4.4 semplificherei ```una previsione dell’insorgenza futura di variazioni significative di flussi di persone```
- Nel punto 4.4, secondo punto, aggiungerei **heat-map** nel glossario, e semplificherei un pò tutta la frase
- Ho notato discrepanza fra il grassetto e il corsivo utilizzato per le Tecnologie coinvolte in differenti capitolati (quelli successivi al C3).
- In generale sarebbe meglio utilizzare i comandi creati (es Omicron), ma questo più per i prossimi documenti

2020-12-15 16:13 UTC, MatthewBalzan requested changes
- Inconsistenza del corsivo nelle informazioni generali (consiglierei di piuttosto non metterlo, lo userei per termini con piu parole come “real time monitoring”, ma bisognerebbe essere consistenti con il resto del documento, quindi sarebbe da mettersi d’accordo)
- 5.2 Riuscire invece che riusire
- 5.3-.5 forse aggiungere query al glossario
- 5.4 Varie invece che vare
- 5.5 Aggiungere Cluster al glossario (e magari anche Force Field, ma non saprei che definizione mettere)
- 5.6 Futuro invece che fututo
- 6.3 Aggiungere Deployment e real time monitoring al glossario 
- 6.4 aggiungere know-how al glossario
- 6.5 Input invece che Inuput 
- 7.x Aggiungerei Multiplayer e singleplayer al glossario
- 7.2 real time invece che realtime (che metterei nel glossario)
- 7.2 dispositivi mobili invece che device mobile
- 7.3 Non saprei se mettere le stesse definizioni anche nel glossario
- 7.3 Swift e kotlin : ‘per sviluppare app’ (senza apostrofo)
- 7.4 Metterei ‘popolari’ invece che ripetere ‘richieste’
- 8.2 Utilizzare invece che utilizare
- 8.5 Permetta invece che peremetta

2020-12-17 21:36 UTC, MatthewBalzan approved these changes

2020-12-17 21:37 UTC, MatthewBalzan commented
Verifica intero documento

2020-12-28 18:14 UTC, merged